version: '3'

services:
  samba:
    container_name: samba
    image: dperson/samba
    environment:
      TZ: 'Europe/Rome'
    network_mode: bridge
    tmpfs:
      - /tmp
      - /run
      - /var/cache/samba/
      - /var/log/samba/
    restart: unless-stopped
    ports:
      - "139:139"
      - "445:445"
    stdin_open: true
    tty: true
    volumes:
      - ../../docker:/docker
      - ./data:/etc/samba
    command: '-u "core;core;500;500" -s "docker;/docker;yes;no;no;core"'
