services:
  phpliteadmin:
    image: ojooss/phpliteadmin:latest
    volumes:
      - "../dbs:/dbs"
    environment:
      PHPLITEADMIN_PASSWORD: ${PHPLITEADMIN_PASSWORD}
      PHPLITEADMIN_THEME: 'Sheep'
      PHPLITEADMIN_LANGUAGE: 'en'
      PHPLITEADMIN_DIRECTORY: '/dbs'
      #PHPLITEADMIN_DATABASES: '[{"path":"/dbs/sample.db","name":"Sample"}]'
      PHPLITEADMIN_ROWSNUM: '50'
      PHPLITEADMIN_CHARSNUM: '500'
      PHPLITEADMIN_MAXSAVEDQUERIES: '20'
      PHPLITEADMIN_COOKIE_NAME: 'pla'
      #PHPLITEADMIN_DEBUG: 'true'
    env_file:
      - .env
    ports:
      - "3080:80"
    restart: unless-stopped
