version: '3'

services:
  caddy:
    container_name: caddy
    build: .
    image: caddy:mine
    volumes:
      - ./data/sql:/db
      - ./data/web:/srv
      - ./data/ssl:/root/.caddy
    restart: always
    ports:
      - "80:80"
    network_mode: bridge

