version: '3'

services:
  blynk:
    container_name: blynk
    build: .
    image: blynk/mine
    restart: always
    volumes:
      - ./data/data:/blynk/data
      - ./data/config:/blynk/config
      - ./data/logs:/blynk/logs
    ports:
      - "7443:7443/tcp"
      - "8080:8080/tcp"
      - "8081:8081/tcp"
      - "8082:8082/tcp"
      - "8440:8440/tcp"
      - "8441:8441/tcp"
      - "8442:8442/tcp"
      - "8443:8443/tcp"
      - "9443:9443/tcp"
    network_mode: bridge

