version: '3'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    command: --admin-password $PASSWORD -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    restart: always
    ports:
      - "9000:9000"
    network_mode: bridge

