version: '3'

services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=$PASSWORD
    volumes:
      - ./data:/var/lib/grafana
    restart: always
    user: "472"
    ports:
      - "3000:3000"
    network_mode: bridge

