version: '3'

services:
  nodered:
    container_name: nodered
    build: .
    image: nodered/mine:slim-v8
    volumes:
      - ./data:/data
    restart: always
    ports:
      - "1880:1880"
    network_mode: bridge

