services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - /run/udev:/run/udev:ro
      - /etc/hosts:/etc/hosts:ro
    environment:
      - TZ=${TZ}
    devices:
      - /dev/serial/by-id/${DEVICE}:/dev/ttyACM0
    ports:
      - "9099:9099"
