version: '3'

services:
  homeassistant:
    environment:
      - TZ=Europe/Rome
    container_name: homeassistant
    image: homeassistant/home-assistant
    volumes:
      - ./data:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    ports:
      - "8123:8123"
    network_mode: bridge

  hassconfigurator:
    container_name: hassconfigurator
    image: causticlab/hass-configurator-docker:x86_64-0.3.1
    volumes:
      - ./data:/config
      - ./data/:/hass-config
    restart: always
    ports:
      - 3218:3218/tcp
    network_mode: bridge

